apiVersion: apps/v1
kind: Deployment
metadata:
  name: meals-web-client
  namespace: default
  labels:
    k8s-app: meals-web-client
    app.kubernetes.io/name: meals-web-client
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: meals-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: meals-web-client
  template:
    metadata:
      labels:
        k8s-app: meals-web-client
      name: meals-web-client
    spec:
      containers:
      - name: meals-web-client
        image: grubplanner.co.uk:32000/meals_web_client
        imagePullPolicy: Always
        env:
        - name: VITE_REPOSITORY_URL
          value: http://meals
        ports:
        - containerPort: 3000
        securityContext:
          privileged: false