apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- secrets.yaml

commonLabels:
  app.kubernetes.io/name: meals
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: meals-platform