apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: meals-ingress
  app.kubernetes.io/component: ingress
  app.kubernetes.io/part-of: meals-platform