apiVersion: v1
kind: Secret
metadata:
  name: meals-database-secret
  namespace: default
  labels:
    app.kubernetes.io/name: meals
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: meals-platform
type: Opaque
data:
  # Base64 encoded values - Replace with your actual values
  username: <BASE64_ENCODED_DB_USERNAME>
  password: <BASE64_ENCODED_DB_PASSWORD>

---
apiVersion: v1
kind: Secret
metadata:
  name: meals-redis-secret
  namespace: default
  labels:
    app.kubernetes.io/name: meals
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: meals-platform
type: Opaque
data:
  # Base64 encoded values - Replace with your actual values
  password: <BASE64_ENCODED_REDIS_PASSWORD>

---
apiVersion: v1
kind: Secret
metadata:
  name: meals-google-oauth-secret
  namespace: default
  labels:
    app.kubernetes.io/name: meals
    app.kubernetes.io/component: oauth
    app.kubernetes.io/part-of: meals-platform
type: Opaque
data:
  # Base64 encoded values - Replace with your actual values
  client-id: <BASE64_ENCODED_GOOGLE_CLIENT_ID>
  client-secret: <BASE64_ENCODED_GOOGLE_CLIENT_SECRET>

---
apiVersion: v1
kind: Secret
metadata:
  name: meals-app-secret
  namespace: default
  labels:
    app.kubernetes.io/name: meals
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: meals-platform
type: Opaque
data:
  # Base64 encoded values - Replace with your actual values
  token-secret: <BASE64_ENCODED_TOKEN_SECRET>

# To encode values in Base64:
# echo -n "your-secret-value" | base64